language: node_js
node_js:
 - 12

addons:
    chrome: stable

script:
  - npm install
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
  - npm run build -- --base-href /Anthony-31/projet-angular.git/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: master

